targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        options:
          auto_register: true
          # Generates for files ending in .dart
          generate_for:
            - lib/app/di/injection.dart
